# Generated by Django 5.0.2 on 2024-02-15 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movies',
            fields=[
                ('backdrop_path', models.TextField(null=True)),
                ('genre_ids', models.JSONField()),
                ('id', models.BigIntegerField(primary_key=True, serialize=False, unique=True)),
                ('overview', models.TextField()),
                ('poster_path', models.TextField()),
                ('release_date', models.DateField()),
                ('title', models.TextField()),
                ('vote_average', models.FloatField(default=0.0)),
                ('vote_count', models.BigIntegerField(default=0)),
            ],
        ),
    ]
