# Generated by Django 5.0.2 on 2024-02-16 00:50

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_rename_movies_movie'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='id',
            field=models.BigIntegerField(default=api.models.generate_unique_id, primary_key=True, serialize=False, unique=True),
        ),
    ]
