# Generated by Django 5.0.2 on 2024-03-11 16:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_user_password'),
        ('api', '0008_alter_user_disliked_movies_alter_user_liked_movies'),
    ]

    operations = [
    ]
